site_name: Sakawish

theme:
  name: material
  features:
    - navigation.indexes
    - navigation.tabs
  palette:
    scheme: sakawish
    # Palette toggle for automatic mode
    # - media: "(prefers-color-scheme)"
    #   toggle:
    #     icon: material/brightness-auto
    #     name: 当前为跟随系统，点击切换为浅色模式

    # # Palette toggle for light mode
    # - media: "(prefers-color-scheme: light)"
    #   scheme: sakawish
    #   toggle:
    #     icon: material/brightness-7
    #     name: 当前为浅色模式，点击切换为深色模式

    # # Palette toggle for dark mode
    # - media: "(prefers-color-scheme: dark)"
    #   scheme: sakawish-dark
    #   toggle:
    #     icon: material/brightness-4
    #     name: 当前为深色模式，点击切换为跟随系统
  font:
    text: Josefin Sans
  language: zh
  logo: res/drawable/ic_sakawish.png
  favicon: res/drawable/ic_sakawish.png

extra_css:
  - stylesheets/extra.css

markdown_extensions:
  - pymdownx.highlight:
      anchor_linenums: true
      line_spans: __span
      pygments_lang_class: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.superfences
  - attr_list
  - md_in_html
  - admonition

plugins:
  - search

nav:
  - 首页: 
    - index.md
    - 特别致谢: sakawish/thanks.md
    - 了解作者: sakawish/sakawish.md
  - 软件:
    - apps/index.md
    - Salt Player（椒盐音乐）:
      - apps/salt-player/index.md
      - 相关系统适配问题: apps/salt-player/adaptation.md
    - Salt Player for Windows:
      - apps/spw/index.md
      - apps/spw/audio-engine.md
    - 椒盐笔记: apps/salt-note.md
    - 心事卷轴:
      - apps/emo-scroll/index.md
  - 开源:
    - open-source/index.md
    - SaltUI:
      - open-source/salt-ui/index.md
      - 设计: open-source/salt-ui/design.md
      - 文档: open-source/salt-ui/doc.md
      - Util: open-source/salt-ui/util.md
  - 音频:
    - audio/index.md
    - audio/play-device.md
    - DSD: audio/DSD.md
  - 开发:
    - dev/index.md
  - 文学:
    - literature/index.md
    - 陈书:
      - 后主: literature/陈书/后主.md
    - 江南春赋: literature/江南春赋.md

extra:
  generator: false

copyright: Copyright &copy; 2020 - 2024 Sakawish 保留所有权利。本站内容未经允许不得转载。