site_name: Sakawish

theme:
  name: material
  features:
    - navigation.indexes
    - navigation.tabs
  palette:
    primary: white
  font:
    text: Josefin Sans

markdown_extensions:
  - pymdownx.highlight:
      anchor_linenums: true
      line_spans: __span
      pygments_lang_class: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.superfences

nav:
  - Sakawish: 
    - index.md
    - 特别致谢: sakawish/thanks.md
  - 软件:
    - apps/index.md
    - Salt Player（椒盐音乐）: apps/salt-player.md
    - 椒盐笔记: apps/salt-note.md
  - 开源:
    - open-source/index.md
    - SaltUI: 
      - open-source/salt-ui/index.md
      - 设计: open-source/salt-ui/design.md
      - 文档: open-source/salt-ui/doc.md
  - 音频:
    - audio/index.md
    - audio/play-device.md
    - DSD: audio/DSD.md
  - 开发:
    - dev/index.md
  - 文学:
    - literature/index.md
    - 陈书:
      - 后主: literature/陈书/后主.md
    - 江南春赋: literature/江南春赋.md

extra:
  generator: false

copyright: Copyright &copy; 2020 - 2024 Sakawish