site_name: Sakawish

theme:
  name: material
  features:
    - navigation.indexes
    - navigation.tabs
  palette:
    primary: white
  font:
    text: Josefin Sans

nav:
  - Sakawish: index.md
  - 软件:
    - apps/index.md
    - Salt Player（椒盐音乐）: apps/salt-player.md
    - 椒盐笔记: apps/salt-note.md
  - 开源:
    - open-source/index.md
    - SaltUI: open-source/salt-ui.md
  - 文学:
    - literature/index.md
    - 陈书:
      - 后主: literature/陈书/后主.md

extra:
  generator: false

copyright: Copyright &copy; 2020 - 2024 Sakawish